#
#  Copyright (c) 2019 Siddharth Chandrasekaran <siddharth@embedjournal.com>
#
#  SPDX-License-Identifier: Apache-2.0
#

dist: bionic
sudo: require
os:
  - linux

language: c

compiler:
  - gcc
  - clang

install: cmake

before_script:
  - pip install -r doc/requirements.txt
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make check
